package Chapter7Sorting.Harmancode;

import java.util.Scanner;

public class ShellSortApp {
	
	public static void main(String[] args){
		Scanner sc=new Scanner(System.in);
		System.out.println("Enter the number of items to be generated by Math random");
		int count=sc.nextInt();
		sc.close();
		ArraySH sh=new ArraySH(count);
		for(int i=1;i<=count;i++){
			
			int n = (int) (java.lang.Math.random() * 99);
			sh.insert(n);
		}
		
		sh.display();
		sh.shellSort();
		sh.display();
	}

}


class ArraySH{
	private int[] arrsh;
	private int nElemns;
	
	ArraySH(int count){
		arrsh=new int[count];
		nElemns=0;
	}
	
	public void insert(int a){
		arrsh[nElemns++]=a;
		
	}
	
	public void display(){
		for(int i=0;i<nElemns;i++){
			System.out.print(arrsh[i]+" ");
		}
		System.out.println("");
	}
	
	public void shellSort(){
		
		int h=0;
		int inner,outer=0;
		
		while(h<=(nElemns/3)){
			h=3*h +1;
		}
		
		while(h>0){
			
			for(outer=h;outer<nElemns;outer++){
				int temp=arrsh[outer];
				inner=outer;
				
				while(inner>=h &&arrsh[inner-h]>temp ){
					arrsh[inner]=arrsh[inner-h];
					inner -=h;
				}
				arrsh[inner]=temp;
				
			}
			
			h=(h-1)/3;
		}
	}
	
}
      